name = "eco-marina"
account_id = "bace0682525d63a4e564f456e50c157c"
compatibility_date = "2024-08-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "eco-marina-admin"
database_id = "44cf3247-4cb1-48b1-956c-5c057d68ad8a"

[[kv_namespaces]]
binding = "SETTINGS"
id = "0c4554f2657741109b2f20a532826826"
